/* Emits include/iswprint_table.h: a two-level bitmap of glibc iswprint()
 * under C.UTF-8 over all Unicode scalar values. 256 code points per block;
 * duplicate 32-byte blocks are deduped via an index table. Run via
 * scripts/gen-tables.sh; commit the generated header. The conformance suite
 * (vs the system wc) catches drift between this table and the runtime glibc. */
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wctype.h>

#define NCP 0x110000
#define BLOCK 256
#define NBLOCKS (NCP / BLOCK)
#define BBYTES (BLOCK / 8)

/* Mirror of isSepCp in include/words.h (the probe-pinned wc separator set);
 * keep the two in sync. */
static int is_sep(unsigned cp, int nbspace)
{
  if (cp == 0x20 || (cp >= 0x09 && cp <= 0x0D)) return 1;
  if (cp == 0x1680 || (cp >= 0x2000 && cp <= 0x200A && cp != 0x2007) ||
      cp == 0x205F || cp == 0x3000)
    return 1;
  if (nbspace && (cp == 0x00A0 || cp == 0x2007 || cp == 0x202F || cp == 0x2060))
    return 1;
  return 0;
}

/* The AVX2 words kernel vectorizes exactly: ASCII, plus well-formed 2-byte
 * sequences whose lead is "clean". Its in-vector model classifies U+0080-009F
 * as non-printable (the C2 window), U+00A0 as separator when nbspace is on
 * (printable when off), and every other 2-byte code point as printable word
 * content. A lead byte is a CANDIDATE (forces the block to the scalar
 * classifier) if any code point it can begin deviates from that model in
 * either nbspace mode. 3/4-byte leads and invalid bytes are candidates
 * unconditionally: the vector path doesn't model them. */
static int cand_lead(unsigned lead)
{
  unsigned c2, nb;
  if (lead < 0x80) return 0;                 /* ASCII: never consulted */
  if (lead < 0xC2 || lead > 0xDF) return 1;  /* not a 2-byte lead */
  for (c2 = 0x80; c2 <= 0xBF; ++c2) {
    unsigned cp = ((lead & 0x1Fu) << 6) | (c2 & 0x3Fu);
    int tp = !!iswprint((wint_t)cp);
    for (nb = 0; nb <= 1; ++nb) {
      int ts = is_sep(cp, (int)nb);
      /* model: 0 = separator, 1 = printable, 2 = other (non-printable) */
      int model = (lead == 0xC2 && c2 <= 0x9F) ? 2
                : (lead == 0xC2 && c2 == 0xA0 && nb) ? 0
                : 1;
      int truth = ts ? 0 : tp ? 1 : 2;
      if (model != truth) return 1;
    }
  }
  return 0;
}

int main(void)
{
  if (!setlocale(LC_CTYPE, "C.UTF-8") && !setlocale(LC_CTYPE, "C.utf8")) {
    fprintf(stderr, "no C.UTF-8 locale available\n");
    return 1;
  }
  static unsigned char blocks[NBLOCKS][BBYTES];
  for (unsigned cp = 0; cp < NCP; ++cp) {
    if (cp >= 0xD800 && cp <= 0xDFFF) continue; /* surrogates: leave 0 */
    if (iswprint((wint_t)cp))
      blocks[cp / BLOCK][(cp % BLOCK) / 8] |= (unsigned char)(1u << (cp % 8));
  }
  /* Dedupe blocks. */
  static unsigned short index[NBLOCKS];
  static unsigned char uniq[NBLOCKS][BBYTES];
  unsigned nuniq = 0;
  for (unsigned b = 0; b < NBLOCKS; ++b) {
    unsigned u;
    for (u = 0; u < nuniq; ++u)
      if (memcmp(blocks[b], uniq[u], BBYTES) == 0) break;
    if (u == nuniq) memcpy(uniq[nuniq++], blocks[b], BBYTES);
    index[b] = (unsigned short)u;
  }
  printf("// GENERATED by scripts/gen-tables.sh -- do not edit.\n");
  printf("// glibc iswprint() under C.UTF-8, two-level bitmap.\n");
  printf("#pragma once\n#include \"typedef.h\"\n\n");
  printf("static const u16 kIswprintIndex[%u] = {\n", NBLOCKS);
  for (unsigned b = 0; b < NBLOCKS; ++b)
    printf("%u,%s", index[b], (b % 16 == 15) ? "\n" : "");
  printf("};\n\nstatic const u8 kIswprintBlocks[%u][%u] = {\n", nuniq, BBYTES);
  for (unsigned u = 0; u < nuniq; ++u) {
    printf("{");
    for (unsigned i = 0; i < BBYTES; ++i) printf("0x%02X,", uniq[u][i]);
    printf("},\n");
  }
  printf("};\n\n");
  printf("inline bool qwcIswprint( const u32 cp )\n{\n");
  printf("  if ( cp >= 0x110000 ) return false;\n");
  printf("  const u8* block = kIswprintBlocks[kIswprintIndex[cp >> 8]];\n");
  printf("  return ( block[( cp & 0xFF ) >> 3] >> ( cp & 7 ) ) & 1;\n}\n");
  printf("\n// Candidate leads for the AVX2 words kernel: 1 = a byte that may\n");
  printf("// begin a code point the in-vector 2-byte model misclassifies (or\n");
  printf("// that is not a 2-byte lead at all), so its block must take the\n");
  printf("// scalar path. See cand_lead() in scripts/gen-iswprint-table.c.\n");
  printf("static const u8 kCandLead[256] = {\n");
  for (unsigned b = 0; b < 256; ++b)
    printf("%d,%s", cand_lead(b), (b % 32 == 31) ? "\n" : "");
  printf("};\n");
  return 0;
}
